<?php

namespace App\Filament\App\Resources\MenuItemAnalyses;

use App\Filament\App\Resources\MenuItemAnalyses\Pages\CreateMenuItemAnalysis;
use App\Filament\App\Resources\MenuItemAnalyses\Pages\EditMenuItemAnalysis;
use App\Filament\App\Resources\MenuItemAnalyses\Pages\ListMenuItemAnalyses;
use App\Filament\App\Resources\MenuItemAnalyses\Pages\ViewMenuItemAnalysis;
use BackedEnum;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Resources\Resource;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Columns\IconColumn;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;
use Modules\Restaurants\Models\MenuItemAnalysis;
use UnitEnum;

class MenuItemAnalysisResource extends Resource
{
    protected static ?string $model = MenuItemAnalysis::class;

    protected static string|UnitEnum|null $navigationGroup = 'Menu';

    protected static string|BackedEnum|null $navigationIcon = Heroicon::OutlinedChartPie;

    protected static ?string $navigationLabel = 'Meal Analyses';

    protected static ?string $recordTitleAttribute = 'menuItem.name';

    public static function form(Schema $schema): Schema
    {
        return $schema->components([
            Section::make('Meal')
                ->components([
                    Select::make('menu_item_id')
                        ->label('Menu item')
                        ->relationship('menuItem', 'name')
                        ->searchable()
                        ->preload()
                        ->required()
                        ->unique(ignoreRecord: true),

                    TextInput::make('total_grams')
                        ->label('Total weight')
                        ->numeric()
                        ->required()
                        ->suffix('g'),
                ])
                ->columns(2),

            Section::make('Macronutrients')
                ->columns(3)
                ->components([
                    TextInput::make('energy_kcal')->numeric()->suffix('kcal'),
                    TextInput::make('protein_g')->label('Protein')->numeric()->suffix('g'),
                    TextInput::make('fat_total_g')->label('Fat')->numeric()->suffix('g'),
                    TextInput::make('carbs_g')->label('Carbs')->numeric()->suffix('g'),
                    TextInput::make('fiber_g')->label('Fiber')->numeric()->suffix('g'),
                    TextInput::make('sugars_total_g')->label('Sugars')->numeric()->suffix('g'),
                ]),

            Section::make('Micronutrients')
                ->columns(3)
                ->components([
                    TextInput::make('calcium_mg')->label('Calcium')->numeric()->suffix('mg'),
                    TextInput::make('iron_mg')->label('Iron')->numeric()->suffix('mg'),
                    TextInput::make('sodium_mg')->label('Sodium')->numeric()->suffix('mg'),
                    TextInput::make('potassium_mg')->label('Potassium')->numeric()->suffix('mg'),
                    TextInput::make('vitamin_c_mg')->label('Vitamin C')->numeric()->suffix('mg'),
                    TextInput::make('vitamin_a_rae_ug')->label('Vitamin A')->numeric()->suffix('µg'),
                ]),

            Section::make('Data quality')
                ->description('Auto-generated by the analysis run. Editing this by hand won\'t change the underlying totals, and it will be recalculated the next time "Analyze Meal" is clicked.')
                ->components([
                    Textarea::make('warnings')
                        ->label('Missing-data warnings')
                        ->rows(3)
                        ->formatStateUsing(fn ($state) => $state ? json_encode($state, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) : null)
                        ->dehydrateStateUsing(fn ($state) => $state ? json_decode($state, true) : null)
                        ->helperText('e.g. { "iron_mg": ["Onion", "Garlic"] } -- foods that had no value for that nutrient.')
                        ->columnSpanFull(),
                ]),
        ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('menuItem.name')
                    ->label('Menu item')
                    ->searchable()
                    ->sortable()
                    ->weight('medium'),

                TextColumn::make('total_grams')
                    ->label('Weight')
                    ->numeric(2)
                    ->suffix(' g')
                    ->sortable(),

                TextColumn::make('energy_kcal')
                    ->label('Energy')
                    ->numeric(0)
                    ->suffix(' kcal')
                    ->sortable()
                    ->badge()
                    ->color(fn (?string $state): string => match (true) {
                        $state === null => 'gray',
                        (float) $state < 300 => 'success',
                        (float) $state < 600 => 'warning',
                        default => 'danger',
                    })
                    ->placeholder('—'),

                TextColumn::make('protein_g')
                    ->label('Protein')
                    ->numeric(1)
                    ->suffix(' g')
                    ->toggleable()
                    ->placeholder('—'),

                TextColumn::make('carbs_g')
                    ->label('Carbs')
                    ->numeric(1)
                    ->suffix(' g')
                    ->toggleable()
                    ->placeholder('—'),

                TextColumn::make('fat_total_g')
                    ->label('Fat')
                    ->numeric(1)
                    ->suffix(' g')
                    ->toggleable()
                    ->placeholder('—'),

                TextColumn::make('sodium_mg')
                    ->label('Sodium')
                    ->numeric(0)
                    ->suffix(' mg')
                    ->toggleable(isToggledHiddenByDefault: true)
                    ->placeholder('—'),

                IconColumn::make('has_warnings')
                    ->label('Complete')
                    ->state(fn (MenuItemAnalysis $record): bool => blank($record->warnings))
                    ->boolean()
                    ->trueIcon(Heroicon::OutlinedCheckCircle)
                    ->falseIcon(Heroicon::OutlinedExclamationTriangle)
                    ->trueColor('success')
                    ->falseColor('warning')
                    ->tooltip(fn (MenuItemAnalysis $record): ?string => blank($record->warnings)
                        ? 'All nutrients resolved for every ingredient'
                        : 'Some ingredients were missing nutrient data'),

                TextColumn::make('updated_at')
                    ->label('Last analyzed')
                    ->dateTime()
                    ->sortable(),
            ])
            ->defaultSort('updated_at', 'desc');
    }

    public static function getEloquentQuery(): \Illuminate\Database\Eloquent\Builder
    {
        return parent::getEloquentQuery()->with('menuItem');
    }

    public static function getPages(): array
    {
        return [
            'index' => ListMenuItemAnalyses::route('/'),
            'create' => CreateMenuItemAnalysis::route('/create'),
            'view' => ViewMenuItemAnalysis::route('/{record}'),
            'edit' => EditMenuItemAnalysis::route('/{record}/edit'),
        ];
    }
}